### ISSUE TITLE
Orientation Icon not supported for Dark Mode

### ISSUE THREAD

**Issue by cr2007** [baraa-almasri/dsc_logo_generator#1]
One thing I noticed while interacting with the generator, is that there is no logo which changes accordingly when the user changes into Dark Mode.

One suggestion could be that if you use a `.svg` file instead of a `.png` file to make it easier to change the color of the icon when the user changes it into Dark Mode.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/73425927/179551469-ba40fffb-2414-479a-b0cb-17c0703ded84.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/73425927/179551416-f7ba30d2-6259-4e9d-b22e-dcb910bd6866.png">

**NOTE:** The icon appears to have a Blue background as the icon was hovered over it when the image was taken.

**Comment by mbaraa** [comment]
Noted, I will fix this and some other UI issues this weekend!
